version: "3"
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY = minio
      - MINIO_SECRET_KEY = minio
    volumes:
      - minio_data:/data
    command: server /data

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
      - POSTGRES_DB = images
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gate:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - minio
      - kafka
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres

volumes:
  minio_data:
  postgres_data: