version: "3"


services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio_storage:/data
    networks:
      mynetwork:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 1s
      retries: 3
    command: server --address ":9000" --console-address ":9001" /data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - mynetwork

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mynetwork
    command: sh -c "((sleep 15 && kafka-topics --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 3 --topic quick-starter)&) && /etc/confluent/docker/run ">
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 0s
      timeout: 1s
      retries: 2
    networks:
      - mynetwork

  gate:
    build:
      context: .
      dockerfile: ./internal/gate/Dockerfile
    container_name: gate
    environment:
      PG_URL: 'postgres://user:password@postgres:5432/postgres'
      KAFKA_BROKER: 'kafka:9092'
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy



  worker:
    build:
      context: .
      dockerfile: ./internal/worker/Dockerfile
    container_name: worker
    volumes:
      - ./config:/config
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy



volumes:
  pg-data:
  gate:
  worker:
  minio_storage:
  postgres_data:
  zookeeper:

networks:
  mynetwork: