postgres:
  pool_max: 2

minio:
  endpoint: minio:9000
  access_key: 'config'
  secret_key: 'password'
  bucket_name: mts

logger:
  log_level: 'debug'

kafka:
  topic: config-topic
  group_id: worker-group
  brokers:
    - kafka:9092

http:
  port: "8080"
