postgres:
  pool_max: 2
  url: "postgres://user:pass@localhost:5432/postgres"

minio:
  endpoint: localhost:9000
  access_key: accesskey
  secret_key: secretkey
  bucket_name: mts

logger:
  log_level: 'debug'

kafka:
  brokers:
    - localhost:9092
  topic: image-topic
  group_id: worker-group

http:
  port: "8080"
