postgres:
  pool_max: 2

minio:
  endpoint: localhost:9000
  accesskey: accesskey
  secretkey: secretkey
  bucket_name: mts

logger:
  log_level: 'debug'

kafka:
  brokers:
    - kafka:9092
  topic: image-topic
  group_id: worker-group

http:
  port: "8080"
